# Generated by Django 2.1.2 on 2018-10-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('message', models.CharField(max_length=100, verbose_name='留言信息')),
            ],
        ),
    ]
